fix visual v nastavení comboboxy
vylepsit grafy doplnit o stupnici klasickou pokud to pujde
zjistit jetli umi vyskakovaci alerty a kdyžtak dodělat jako v meteo-qt např
language nejdou zjistit proč
větši tečky na grafu+
map je odsazeny zjistit proc mozna konfigurat s pameti možna chybu v ui a další nějak zmenšit setting dialog, možná stejná chyba
možnost zvolit kde se bude zobrazovat notifikace a jak to vubec funguje ??? :-) předělat na linux standard a dal proverit chod pod wayland
maps barvicky temp atd moic nejsouz videt







Do budoucna přidat další stránky třeba CHMU apod ( možnostz nechat si dát request na githubu o implementaci ?), nebo LUA kod pro implementaci
